#config.yaml
#the following fields must be inserted as strings, i.e. in between quotations.
calendarific_api_key : #insert here the api key given when creating a calendarific account.
NASA_api_key : #insert here the api key given when registering for the NASA API
